# Generated by Django 2.0.3 on 2018-08-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loorollv2app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expires_in',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scope',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
